### ISSUE TITLE
Fix the DNS settings with your Domain Provider

### ISSUE THREAD

**Issue by philkuz** [Berkeley-CS61B/sp17#1]
Anyone can hijack datastructur.es by simply writing a github pages website and including a CNAME file w/ datastructur.es

The Kaggle Decal accidentally did this after forking this repo.

**Comment by secant** [comment]
The domain can't get claimed after one repo specifies it as its custom domain. It just so happened that the Kaggle folks forked the repo while we were moving the CNAME to another repo.

**Comment by philkuz** [comment]
ooh ok thanks! always great to learn and I apologize on behalf of my fellow kaggle decal folks
